### ISSUE TITLE
Explain differences from Finite

### ISSUE THREAD

**Issue by bendavies** [winzou/state-machine#1]
Hi,

I'd be interested to know (and maybe add it to the readme) how this library differs from https://github.com/yohang/Finite and what different direction is being taken (why Finate wasn't suitable etc...)

Thanks

**Comment by isaackearl** [comment]
@winzou you mention that "it supports customization of callback's arguments: you can pass any argument you want thanks to the config"

but I can't figure out how to actually pass any arguments to the callback.  I can't find any examples that use the callbacks for anything other then a var_dump.  It would be amazing if you could give me an example.

**Comment by winzou** [comment]
Hi @isaackearl 

When you define your callback, you can pass an array of arguments `args`. Each value of this array will be parsed by the ExpressionLanguage, having `object` (the object undergoing the transition) and `event` (the actual transition event) as variables.

Here is what you could do:

    'on-confirm' => array(
        'on' => array('confirm'), // Will be called only on this transition
        'args' => array('event.getTransition()', 'object.getShipments()'),
        'do' => function($transitionName, ArrayCollection $shipments) {
            printf('%s shipments passed as argument of transition %s.', count($shipments), $transitionName);
        }
    ),

Hope it helps!
