### ISSUE TITLE
Support for anonymous = triggerless = completion transitions

### ISSUE THREAD

**Issue by Gennnji** [winzou/state-machine#32]
Thanks for the great state machine, but often there is a need in triggerless transitions which I can realize here.
Machine may be needed to change its state after some period in time accordingly to some guard condition or just after all activities done when it came to a target state.
Is there a possibility to implement it.
Or maybe I could do this.

**Comment by winzou** [comment]
Hi,
The logic of triggering transitions does not belong to this library. It depends on each application, hence I suggest to implement it on your side ;)
