### ISSUE TITLE
Question: how to set an "initial" state

### ISSUE THREAD

**Issue by cartbeforehorse** [winzou/state-machine#33]
As the question says, how do we set the state machine to an initial state?  It seems an obvious thing to want to do, but I can't find documentation on it, and I don't see any obvious attempt at setting an initial state in your code.

**Comment by winzou** [comment]
Hi,
The initial state lives in your own domain, not in this lib. For example, you can use a default attribute value when defining your class:

    class YourModel
    {
        private $state = 'initial';
    }
