### ISSUE TITLE
Question: what's the best solution to be compatible with an exist numeric state?

### ISSUE THREAD

**Issue by zjsxwc** [winzou/state-machine#34]
hi,
the state of my entities is the property `status` which is an integer number in database.

currently, in order to be compatible and human readable,  i create the method `getState`:
```
// in entity class
private $stateByStatusMap = [
     0 => "new",
     1 => "processing",
     2 => "finish"
];
public function getState(){
      return $this->stateByStatusMap[$this->Status];
}
```

**Comment by winzou** [comment]
Hi,

You can configure the property path for your state. Set it as something like `stateByString` and the StateMachine will use (via the PropertyAccessor) `getStateByString()` and `setStateByString()`. Use these methods to convert the string states of your state machine to the int states of your model, as you described in your post.
