### ISSUE TITLE
Question : difference between Callbacks and Events

### ISSUE THREAD

**Issue by Ali-Kent** [winzou/state-machine#36]
Hello,

What is the difference between callback use and event use ?

**Comment by winzou** [comment]
These are 2 ways to do the same thing: execute something at a specific time.

* Callbacks enable you to call a specific service/method with specific arguments.
* Events enable you to listen everything and use your own logic to filter when to execute something and with which argument.

**Comment by Ali-Kent** [comment]
Ok,

thanks for this response.

2017-12-05 15:26 GMT+01:00 Alexandre Bacco <notifications@github.com>:
