### ISSUE TITLE
Compatibility with symfony/event-dispatcher ^4.3

### ISSUE THREAD

**Issue by sebdesign** [winzou/state-machine#41]
Since 4.3, symfony/event-dispatcher changed the signature of the `EventDispatcherInterface::dispatch()` and removed the `Event` class. These deprecated changes were removed in 5.0. See the [changelog](https://github.com/symfony/event-dispatcher/blob/master/CHANGELOG.md).

Is there a plan to upgrade this package? I am the maintainer of [sebdesign/laravel-state-machine](https://github.com/sebdesign/laravel-state-machine) which is based on this package and I would love to support the newer versions of Symfony and Laravel.

**Comment by winzou** [comment]
Hi,

Can you advise what would you update?

Thanks!

**Comment by sebdesign** [comment]
Hello,

It seems this has been fixed when support for Symfony 5 was added:

https://github.com/winzou/state-machine/commit/2448d9ab850387bc37c7e3540c8141b27029978c#diff-ce5bba7f8290e8a53edaa5f70682554ef452b143f2819b6682e1d4514fe026e8R94

Thanks!
