### ISSUE TITLE
Composer Issue with PHP8

### ISSUE THREAD

**Issue by robertmarney** [winzou/state-machine#47]
Apologies if this is the wrong place. I am having issues installing your package using composer with PHP 8.0.3

```bash
  Problem 1
    - winzou/state-machine[0.4.1, ..., v0.4.x-dev] require php ^7.1.3 -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires winzou/state-machine ^0.4.1 -> satisfiable by winzou/state-machine[0.4.1, v0.4.x-dev].
```

**Comment by winzou** [comment]
Hi,

That's weird, the latest version (0.4.1) also accepts PHP version 8.0: https://packagist.org/packages/winzou/state-machine#0.4.1

**Comment by robertmarney** [comment]
Yes, super strange. I got to the point of spinning up both a new local docker and a digital ocean droplet and both of those instances throw the same error.

**Comment by willhatchVista** [comment]
This is interesting. I'm getting the same error, but when I look at what's in my vendor folder winzou\state-machine\composer.json it's not a match for the file on your latest release
```
    "require": {
        "php":                         "^7.1.3",
        "symfony/event-dispatcher":    "~4.3|~5.0",
```

**Comment by robertmarney** [comment]
@winzou  - This issue is persisting, perhaps tagging a new release will trigger an update?

I also see the same issue on a fresh install that @willhatchVista saw:

![image](https://user-images.githubusercontent.com/48888686/122094758-bee91900-cdc9-11eb-9690-3a7827360610.png)

**Comment by winzou** [comment]
How did you get to that fresh install exactly?

**Comment by robertmarney** [comment]
I cleared my local composer cache then initialized existing project from git  and installed composer via the composer.lock file that requires 0.4.1 of this package. 

![image](https://user-images.githubusercontent.com/48888686/122127880-15b61900-cdf1-11eb-92f5-c38c9ab74346.png)

**Comment by winzou** [comment]
That's really weird. I've created a new tag https://github.com/winzou/state-machine/releases/tag/0.4.2 can you try again?

**Comment by robertmarney** [comment]
Success! That did it. Very strange indeed.

Thank you for your help and the package!

**Comment by winzou** [comment]
Great, thanks for reporting!
