### ISSUE TITLE
Support for php 8.0 or higher

### ISSUE THREAD

**Issue by DanielSpindler** [winzou/state-machine#55]
whenever im trying to use it with 8.0 or higher i get (in the releases is stated that it would already support 8.0)
"   - winzou/state-machine[0.4.1, ..., v0.4.x-dev] require php ^7.1.3 -> your php version (8.0.26) does not satisfy that requirement."

in composer.json:
        "winzou/state-machine": "^0.4",

**Comment by winzou** [comment]
Hi, that's weird, the package supports php 8.0 since its version 0.4.1. Maybe you'll have to clear your composer cache?

**Comment by DanielSpindler** [comment]
Hey, tried that before. Since im upgrading an php 7.4 project to 8.0 i suppose some other pkg is at fault for the error, but doesnt show it. I will let you know if i can resolve it. Thanks for the reply

**Comment by DanielSpindler** [comment]
for now im Closing the Issue since it seems to be a "unique" to me problem
